# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros

Name:       cpio
Summary:    A GNU archiving program
Version:    2.11
Release:    1
Group:      Applications/Archiving
License:    GPLv3+
URL:        http://www.gnu.org/software/cpio/
Source0:    ftp://ftp.gnu.org/gnu/cpio/cpio-%{version}.tar.gz
Source1:    cpio.1
Source100:  cpio.yaml
Patch0:     cpio-2.6-setLocale.patch
Patch1:     cpio-2.9-rh.patch
Patch2:     cpio-2.9-exitCode.patch
Patch3:     cpio-2.9-dev_number.patch
Patch4:     cpio-2.9.90-defaultremoteshell.patch
BuildRequires:  autoconf


%description
GNU cpio copies files into or out of a cpio or tar archive.  Archives
are files which contain a collection of other files plus information
about them, such as their file name, owner, timestamps, and access
permissions.  The archive can be another file on the disk, a magnetic
tape, or a pipe.  GNU cpio supports the following archive formats:  binary,
old ASCII, new ASCII, crc, HPUX binary, HPUX old ASCII, old tar and POSIX.1
tar.  By default, cpio creates binary format archives, so that they are
compatible with older cpio programs.  When it is extracting files from
archives, cpio automatically recognizes which kind of archive it is reading
and can read archives created on machines with a different byte-order.

Install cpio if you need a program to manage file archives.




%prep
%setup -q -n %{name}-%{version}

# cpio-2.6-setLocale.patch
%patch0 -p1
# cpio-2.9-rh.patch
%patch1 -p1
# cpio-2.9-exitCode.patch
%patch2 -p1
# cpio-2.9-dev_number.patch
%patch3 -p1
# cpio-2.9.90-defaultremoteshell.patch
%patch4 -p1
# >> setup

%docs_package

# << setup

%build
# >> build pre
# << build pre

%configure --disable-static \
    --disable-nls

make %{?jobs:-j%jobs}

# >> build post
# << build post
%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install
mkdir -p %{buildroot}%{_mandir}/man1
cp -a %{SOURCE1} %{buildroot}%{_mandir}/man1


# >> install post
mkdir -p $RPM_BUILD_ROOT/bin
ln -sf ../usr/bin/cpio $RPM_BUILD_ROOT/bin/
rm -rf %{buildroot}%{_prefix}/libexec/rmt
# << install post






%files
%defattr(-,root,root,-)
# >> files
%doc COPYING
%{_bindir}/*
/bin/cpio
# << files


